server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: youtoy-apigateway
  cloud:
    gateway:
      routes:
        - id: youtoy-swagger-service
          uri: http://localhost:8080/
          predicates:
            - Path=/swagger-ui/**, /v3/**

        - id: youtoy-service
          uri: http://localhost:8080/
          predicates:
            - Path=/subscribes/**, /memberships/**
          filters:
            - name: CacheRequestBody
              args:
                bodyClass: java.util.LinkedHashMap
            - AuthorizationHeaderFilter

        - id: youtoy-member-service
          uri: http://localhost:8080/
          predicates:
            - Path=/members/**
          filters:
            - name: CacheRequestBody
              args:
                bodyClass: java.util.LinkedHashMap
            - AuthorizationHeaderFilter
            - MemberAuthorizationFilter

        - id: youtoy-channel-service
          uri: http://localhost:8080/
          predicates:
            - Path=/channels/**, /channelManagements/**
          filters:
            - name: CacheRequestBody
              args:
                bodyClass: java.util.LinkedHashMap
            - AuthorizationHeaderFilter
            - ChannelAuthorizationFilter
