server:
  port: 8000

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: youtoy-apigateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: youtoy-service
            uri: http://localhost:8080/
            predicates:
              - Path=/**
